### ISSUE TITLE
Latest update includes aws-sdk

### ISSUE THREAD

**Issue by benasher44** [pyramation/libpg-query-node#18]
Since #17, the build is definitely faster, but now this library depends on the aws-sdk. Is that necessary? aws-sdk is pretty large (73MB). I think something got included somewhere by mistake. There are a lot of other new packages now in here too, all of which seem like they were probably included by mistake.

**Comment by benasher44** [comment]
Actually, the owns downstream of @mapbox/node-pre-gyp seem fine, but it doesn't look like aws-sdk is actually used anywhere. It'd be great to see a patch release with it removed 🙏. Thanks for your help. Looking forward to the faster build!

**Comment by pyramation** [comment]
@benasher44 thanks for the PR! Let me just double check with Div

@darora does this work for you guys?

**Comment by benasher44** [comment]
👍 At minimum, if there is a specific part that is needed, the new AWS SDK 3 is modularized, so you can include just the part that is needed (e.g. `@aws-sdk/<x>`).

**Comment by darora** [comment]
Hmm yeah I think this should be fine-not sure why I included it in the first place. Approving the PR, thanks @benasher44 !

**Comment by benasher44** [comment]
woo thanks!

**Comment by benasher44** [comment]
Would be great to see a patch release soon. Thanks again!

**Comment by pyramation** [comment]
@darora — technically the build didn't change, would the system be able to use previous binaries or do we need to publish new ones? Let me know if you want to publish — and then I can also update plgsql-parser after we update this one to npm

**Comment by pyramation** [comment]
hey @benasher44 and @darora I just published both libraries, but it may not include the faster build until we push the binaries to the supabase cdn.

**Comment by benasher44** [comment]
Awesome, thank you! If you update here when they're uploaded, I'll give the update a try and report back
