### ISSUE TITLE
[Windows] Silent "app crashed" with no error

### ISSUE THREAD

**Issue by dylanplural** [pyramation/libpg-query-node#20]
I've been using this library for months without problem.

Today I pulled our codebase onto a new laptop with freshly installed wsl2.
The application is running in a docker image similar to:
```
FROM node:16.14.2-alpine3.15

RUN apk add gcompat libc6-compat
RUN corepack enable
RUN npm install pm2 -g
RUN pm2 update

CMD ["pm2-runtime", "ecosystem.config.js"]
```

Upon hitting `parseQuerySync` the application silently crashes (exit code 1) with no error message.
At this stage I'm not looking for a fix but simply any way I could get more debugging information out of the library.
I tried `DEBUG=*` with no luck.

**Comment by pyramation** [comment]
Pardon the delay, did you ever get this solved?

**Comment by dylanplural** [comment]
Nope, still not solved, and it's now failed on 2 different laptops. Both wsl2, both using the same docker image.

**Comment by pyramation** [comment]
is `wsl2` a windows/linux vm?

**Comment by dylanplural** [comment]
It's a little more complicated than a vm:

https://learn.microsoft.com/en-us/windows/wsl/about

It's a full linux kernal, shipped inside windows, and executed via docker.

**Comment by dylanplural** [comment]
Finally got to the bottom of this, it's a really small change:

```
apk add libpq
```

Needed adding to the dockerfile.
