### ISSUE TITLE
libpg-query may need an update due to new Xcode causing build failure.

### ISSUE THREAD

**Issue by john-trashlab** [pyramation/libpg-query-node#23]
Builds are broken for me after upgrading Xcode. A fix has been pushed to `libpg-query` in `13-2.2.0`.

See https://github.com/pganalyze/pg_query/issues/263 and https://github.com/pganalyze/libpg_query/commit/1097b2c33e54a37c0d2c0f2d498c7d1cf967eae9

**Comment by pyramation** [comment]
published a fix, will be updating pgpsql-parser asap/next!

```
+ libpg-query@13.3.0
```
