### ISSUE TITLE
Binaries for v13.3.1 Node 16 (v93)

### ISSUE THREAD

**Issue by ruggi99** [pyramation/libpg-query-node#28]
Hi, looking at `https://supabase-public-artifacts-bucket.s3.amazonaws.com/` tha last version uploaded is `v13.3.0`.
Would you mind adding `v13.3.1` for Node 16 `v93`, both linux x64 and arm64?
Also `v14.0.0` and `v15.0.0` would be ideal.
This is preventing me to upgrade some dependencies.

Thanks in advance

**Comment by darora** [comment]
13.3.1 has been uploaded. The pre-built binaries are an optimization, and should not be a blocker for upgrades--it'll fall back to compiling from source if needed.
