### ISSUE TITLE
Fix ARM build

### ISSUE THREAD

**Issue by inian** [pyramation/libpg-query-node#9]
Hi, currently this doesn't build on M1 Mac. This has been fixed in libpg_query in [this commit](https://github.com/pganalyze/libpg_query/commit/55668e9003dfb148bc74b9c5d4a41facc5bad5c7). 

I see that the [current commit](https://github.com/pyramation/libpg-query-node/blob/67866b7850d91d5d7adf17d59dd604372fd7e11d/script/buildAddon.sh#L3) does not have this fix yet. Can you publish a new release with the latest patches from libpq_query? 

If it is as simple as just updating the commit in that file, happy to send a PR too. 

Thanks!

**Comment by pyramation** [comment]
Thanks for the help! @inian please check if the latest works for you `@13.1.1`

**Comment by inian** [comment]
Works now. Thanks a lot Dan!

**Comment by maschwenk** [comment]
@pyramation this is fine for people running node in Rosetta, but if we want to run this natively, it seems currently you are only generating a single binary for Darwin? I was able to compile it myself using the instructions on this repo, but figure it may be easier to just have it done here?

**Comment by pyramation** [comment]
pardon my experience with Rosetta, is this the new mac? 

yea we should probably do a build and push the binary to npm. However, I don't have a rosetta machine so we'll have to collaborate here somehow.

**Comment by maschwenk** [comment]
@pyramation Just messaged you on Keybase

**Comment by maschwenk** [comment]
@inian Just confirming, are you running this in Rosetta or not?

**Comment by karlhorky** [comment]
> this is fine for people running node in Rosetta, but if we want to run this natively, it seems currently you are only generating a single binary for Darwin

Is this still an open issue? When I install + use `libpg-query` via [SafeQL](https://github.com/ts-safeql/safeql) on an M1 (`process.arch === 'arm64'`), it is failing with the following error:

```
dyld[...]: missing symbol called
```

Also reported downstream in SafeQL here: https://github.com/ts-safeql/safeql/issues/65

Or maybe this is unrelated?

**Comment by karlhorky** [comment]
Hmm... actually getting this again now. It seems to be an edge case related to running the installation in a VS Code "Intel Chip" terminal - even though the Node.js version installed on the machine is an `arm64` version.

Reproduction steps:

1. Open an "Intel Chip" version of VS Code on an M1 and open the terminal (the installed version of Node.js should be `arm64` architecture)
2. Clone https://github.com/upleveled/next-js-example-fall-2022/tree/994747b1d24298ff8b27926e34792d7faecdd39f (commit hash `994747b1d24298ff8b27926e34792d7faecdd39f`)
3. Run `yarn` to install `libpg-query` and other dependencies - the installation will succeed
4. Run `yarn eslint . --max-warnings 0` - this will fail with the `dyld[...]: missing symbol called` error as in the output below

```
$ yarn eslint . --max-warnings 0
yarn run v1.22.19
$ /Users/k/projects/next-js-example-fall-2022/node_modules/.bin/eslint . --max-warnings 0
dyld[30868]: missing symbol called
error Command failed with signal "SIGABRT".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

So the solutions / workarounds for this are:

A) Install an "Apple Silicon" or "Universal" version of VS Code

or

B) Run the installation in a terminal running in `arm64` mode
